---
title: "Module 6 Project"
Author: "ButteRflies"
output: html_document
date: "2023-10-17"
bibliography: BIOL3140.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction


# Methods


#### Image acquisition


```{r, message = FALSE}
library(rgbif) 
```

#### Digitization


#### Shape analysis


```{r,"Setting up for Shape Analysis", message = FALSE, results= FALSE}
library(tidyverse)
library(Momocs)

f <- list.files("class_out_data",pattern=".txt|.csv",full.names = TRUE)

out <- read_delim(f[1],delim="\t") %>% 
  as.matrix()
out.df <- vroom::vroom(f, id = "filename")

out.df <- out.df %>% 
  mutate(wing=gsub("XY_.+_(hindwing|forewing)\\..+","\\1",basename(filename))) %>% 
  na.omit()

outs.l <- sapply(f,function(x) out.df %>% filter(filename==x) %>% select(X,Y) %>% as.matrix)

wings <- gsub("XY_.+_(hindwing|forewing)\\..+","\\1",basename(names(outs.l)))
outs <-  outs.l %>% 
  Out(fac=list(wing=wings)) %>% 
  coo_flipx()
forewings <- outs %>% 
  filter(wing=="forewing")

hindwings <- outs %>% 
  filter(wing=="hindwing")

fore.min <- forewings %>% 
  coo_nb() %>% 
  min()

hind.min <- hindwings %>% 
  coo_nb() %>% 
  min()
``` 

```{r, "Preparing for comparative analysis", results = FALSE, message = FALSE}

forewing.pca <- forewings %>%
  coo_interpolate(fore.min) %>%
  coo_align()  %>%
  coo_slide(id=1) %>% 
  fgProcrustes() %>% 
  efourier(norm=FALSE) %>% 
  PCA()

hindwing.pca <-hindwings %>% 
  coo_interpolate(hind.min) %>% 
  coo_align()  %>%
  coo_slide(id=1) %>% 
  fgProcrustes() %>% 
  efourier(norm=FALSE) %>% 
  PCA()

hindwings %>% 
   coo_interpolate(hind.min) %>% 
   coo_align()  %>%
   coo_slide(id=1) %>% 
  fgProcrustes() %>% 
  stack
``` 


#### Comparative analysis


```{r, "Comparative analysis", results = FALSE, message = FALSE, echo=FALSE}
library(ape)

lep.tree <- ape::read.tree("lep_tree2.tre")
lep.tree <- ladderize(lep.tree)

lep.tree$tip.label <- gsub("_"," ",lep.tree$tip.label)
basename(names(outs))[1:5]
lep.sp <- read_csv("lep_image_data.csv")
```

```{r, "Fore- and hindwing PC1 and PC2 stored with species information",results = FALSE, message = FALSE}
out.data <- tibble(xy.file=basename(names(outs))) %>% 
  mutate(identifier=gsub("XY_|_hindwing|_forewing|.txt","",xy.file)) %>% 
  left_join(lep.sp)
hindwing.pca2 <-  tibble(xy.file=basename(rownames(hindwing.pca$x)),PC1=hindwing.pca$x[,1],PC2=hindwing.pca$x[,2]) %>% 
  left_join(out.data)
forewing.pca2 <-  tibble(xy.file=basename(rownames(forewing.pca$x)),PC1=forewing.pca$x[,1],PC2=forewing.pca$x[,2])%>% 
  left_join(out.data)
```


#### Evolutionary rates



```{r, results = FALSE, message = FALSE}
drops <- lep.tree$tip.label[!lep.tree$tip.label%in%unique(out.data$species)]
lep.tree2 <- drop.tip(lep.tree,drops)

#PC1s
hind.pc1 <- hindwing.pca2 %>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC1=mean(PC1)) %>% 
  pull

names(hind.pc1) <-  hindwing.pca2%>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC1=mean(PC1)) %>% 
  pull(species)

fore.pc1 <- forewing.pca2 %>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC1=mean(PC1)) %>% 
  pull(PC1)

names(fore.pc1) <-  forewing.pca2 %>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC1=mean(PC1)) %>% 
  pull(species)

#PC2s
hind.pc2 <- hindwing.pca2 %>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC2=mean(PC2)) %>% 
  pull(PC2)

names(hind.pc2) <-  hindwing.pca2%>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>%
  summarize(PC2=mean(PC2)) %>% 
  pull(species)

fore.pc2 <- forewing.pca2 %>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC2=mean(PC2)) %>% 
  pull(PC2)

names(fore.pc2) <-  forewing.pca2 %>% 
  filter(species%in% lep.tree2$tip.label) %>% 
  group_by(species) %>% 
  summarize(PC2=mean(PC2)) %>% 
  pull(species)
```


#### Shifts in evolutionary rates


```{r, results = FALSE, message = FALSE}
library(RRphylo)
hindPC1.RR <- RRphylo(tree=lep.tree2,y=hind.pc1)
hindPC1.SS<- search.shift(RR=hindPC1.RR,status.type="clade")
```
```{r, results = FALSE, message = FALSE}
hindPC1.plot <- plotShift(RR=hindPC1.RR,SS=hindPC1.SS)

forePC1.plot <- plotShift(RR=hindPC1.RR,SS=hindPC1.SS)


library(ggtree)
library(wesanderson)

plot_SS <- function(tre=NULL,SS=NULL,tax=NULL){
  
  nodes <- as.numeric(rownames(SS$single.clades))
  
  pal <- wes_palette("Zissou1",n=length(nodes))
  sp <- list()
  for(i in nodes){
    sp.i <- extract.clade(tre,i)$tip.label
    
    sub.names <- lapply(tax,function(x) x[x%in%sp.i]) 
    
    in.clades <- lapply(sub.names,function(x) length(x)>0) 
    all.of.clade <- lapply(sub.names,function(x) all(sapply(sp.i,function(z) z%in%x))) 
    
    high.clade <- names(sub.names)[last(which(all.of.clade==T))]
    all.clades <- names(sub.names)[which(in.clades==T)]
    crown <- ""
    if(high.clade!=last(names(sub.names))) crown <- "crown-"
    
    sub.clades <- NULL
    if(length(grepl("oidea",all.clades))>0) sub.clades <- all.clades[grepl("oidea",all.clades)]

    high.clade2 <- paste0(crown,high.clade,": ",paste0(sub.clades,collapse = "+"))
    sp[[paste0(i)]] <- tibble(n=i,species=sp.i,clade=high.clade2)
    
  }

  d <- do.call(rbind,sp)%>% 
    rename(label=species) 
  
  d2<- d %>% rename(clade_name=clade) 
  
  p <- ggtree(tre)+ scale_y_reverse()
  
  p$data <- p$data %>% left_join(d) %>% left_join(tibble(node=nodes,SS$single.clades) %>% mutate(shift=ifelse(rate.difference>0,"+","-")))
  
  p <-  p+geom_tiplab(aes(col=clade),geom="text",size=1.2)+
    geom_cladelab(data=d2,mapping=aes(node=n,col=clade_name,label=clade_name),offset=1,size=1.5)+
    geom_hilight(data=d2,mapping = aes(node = n,fill=clade_name),alpha = 0.01)+
    scale_fill_manual(values = pal)+
    scale_color_manual(values = pal)+
    theme(legend.position = "none")+geom_nodepoint(mapping=aes(subset = shift =="-"), size=5, shape=25,fill='blue',color='blue',alpha=0.7)+
    geom_nodepoint(mapping=aes(subset = shift =="+"), size=5, shape=24, fill='red',color='red',alpha=0.7)
  p <- p+xlim(NA,6)
  res <- tibble(n=nodes,SS$single.clades) %>% left_join(d %>% select(n,clade) %>% unique)
  
  return(list(plot=p,res=res))
  
}

tax.names <- readRDS("Lep_classification.RDS")

hindPC1.res <- plot_SS(lep.tree2,hindPC1.SS,tax = tax.names)
```

#### Shape evolution correlation


```{r, "PC1", results = FALSE, message = FALSE}
#PC1
hindPC1.pic <- pic(hind.pc1,phy = lep.tree2)
forePC1.pic <- pic(fore.pc1,phy = lep.tree2)

PC1.pic <- tibble(
  hind=hindPC1.pic,
  fore=forePC1.pic
)
```

```{r,"PC2", results = FALSE, message = FALSE}
#PC2
hindPC2.pic <- pic(hind.pc2,phy = lep.tree2)
forePC2.pic <- pic(fore.pc2,phy = lep.tree2)

PC2.pic <- tibble(
  hind=hindPC2.pic,
  fore=forePC2.pic
)
```

# Results

#### Evolutionary Rates

```{r, "Load tree, drop tips not in PCA data", results = FALSE, message = FALSE, fig.cap="The Lepidopteran phylogenetic tree"}

plot(lep.tree,cex=0.1)

```


```{r, "Wing PC evolutionary rates",message=FALSE,results=FALSE}

library(phytools)
forePC1.BM<-brownie.lite(lep.tree2,fore.pc1*10)
hindPC1.BM<-brownie.lite(lep.tree2,hind.pc1*10)

forePC2.BM<-brownie.lite(lep.tree2,fore.pc2*10)
hindPC2.BM<-brownie.lite(lep.tree2,hind.pc2*10)
```

```{r, "Comparing PC wing evolutionary rates"}
#Comparing PC1 wing evolutionary rates
forePC1.BM$sig2.single
hindPC1.BM$sig2.single

#Comparing PC2 wing evolutionary rates
forePC2.BM$sig2.single
hindPC2.BM$sig2.single
```

#### Evolutionary Rate Shifts

```{r, "Tree with exceptional shift highlighted",echo=FALSE,fig.cap="Figure 1: Lepidoptera phylogenetic tree with lineages with exceptional shifts indicated by a triangle. Blue and downward triangle signifies a low shift."}
hindPC1.res$plot
```
```{r, "Scale of shift", echo=FALSE, fig.cap = "The scale of the shift"}
hindPC1.res$res
```

#### Correlation of wing shape evolution

```{r, "Regression of transformed PC1 values", message=FALSE, echo=FALSE,fig.cap="Figure 2: Linear regression of PIC-transformed PC1 values"}
PC1.pic %>% 
  ggplot(aes(x=fore,y=hind))+geom_point()+geom_smooth(method="lm")
```
```{r,echo=FALSE, "Summary of linear model of transformed PC1 values"}
summary(lm(hind~fore,PC1.pic))
```

```{r, "Regression of transformed PC2 values", message=FALSE, echo=FALSE, fig.cap="Figure 3: Linear regression of PIC-transformed PC2 values"}
PC2.pic %>% 
  ggplot(aes(x=fore,y=hind))+geom_point()+geom_smooth(method="lm")
```
```{r,"Summary of linear model of PC2", echo=FALSE}
summary(lm(hind~fore,PC2.pic))
```



# Discussion



# Author Contributions


# References
